---
- name: ex4
  gather_facts: off
  hosts: arista
  tasks:
    - name: capture show
      eos_command:
        commands: show mac address-table | json
      register: out

    - name: print show
      debug:
        var: out

    - name: map elements
      set_fact:
        mac_addr: "{{ out.stdout[0]['unicastTable']['tableEntries']  }}"

    - name: combine elements
      set_fact:
        combined_elem: "{{ combined_elem | default([]) + [item['macAddress']] }}"
      loop: "{{ mac_addr }}"

    - name: print combined elems
      debug:
        var: combined_elem



